import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — ToolPilot",
  description: "ToolPilot terms of service. Read the terms and conditions for using our free online tools.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <h1 className="mb-6 text-3xl font-bold">Terms of Service</h1>
      <p className="mb-4 text-sm text-gray-500">Last updated: March 27, 2026</p>

      <div className="space-y-6 text-gray-600">
        <section>
          <h2 className="mb-2 text-xl font-semibold text-gray-900">Acceptance of Terms</h2>
          <p>
            By accessing and using ToolPilot (toolpilot.pages.dev), you accept and
            agree to be bound by these Terms of Service. If you do not agree to
            these terms, please do not use our website.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-gray-900">Description of Service</h2>
          <p>
            ToolPilot provides free online tools for text processing, development,
            conversion, and other utilities. All tools operate client-side in your
            browser. The service is provided &quot;as is&quot; without warranties of any
            kind.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-gray-900">Use of the Service</h2>
          <p>You agree to use ToolPilot only for lawful purposes. You may not:</p>
          <ul className="mt-2 list-inside list-disc space-y-1">
            <li>Use the service for any illegal or unauthorized purpose</li>
            <li>Attempt to interfere with the proper functioning of the website</li>
            <li>Scrape, crawl, or use automated means to access the service in a manner that burdens our infrastructure</li>
            <li>Reverse engineer or attempt to extract the source code of our tools beyond what is publicly visible</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-gray-900">Disclaimer of Warranties</h2>
          <p>
            ToolPilot is provided on an &quot;as is&quot; and &quot;as available&quot; basis. We make no
            warranties, expressed or implied, regarding the accuracy, reliability,
            or availability of any tool or feature. Use the tools at your own risk.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-gray-900">Limitation of Liability</h2>
          <p>
            In no event shall ToolPilot be liable for any indirect, incidental,
            special, consequential, or punitive damages arising from your use of
            or inability to use the service, including but not limited to data
            loss, errors in output, or service interruptions.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-gray-900">Intellectual Property</h2>
          <p>
            The ToolPilot name, logo, and website design are our intellectual
            property. The output generated by our tools belongs to you — we claim
            no ownership over content you create using our tools.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-gray-900">Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Changes will
            be effective immediately upon posting to this page. Your continued use
            of the service after any changes constitutes acceptance of the new
            terms.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-gray-900">Contact</h2>
          <p>
            If you have questions about these terms, contact us at{" "}
            <span className="font-medium text-gray-900">toolpilot.contact@gmail.com</span>.
          </p>
        </section>
      </div>
    </div>
  );
}
