"use client";

import { useState, useRef } from "react";
import QRCode from "qrcode";
import AdBanner from "@/components/AdBanner";
import Breadcrumb from "@/components/Breadcrumb";
import FAQ from "@/components/FAQ";
import JsonLd, { howToSchema, webApplicationSchema } from "@/components/JsonLd";

const faqs = [
  {
    question: "What is a QR code?",
    answer:
      "A QR (Quick Response) code is a two-dimensional barcode that can store URLs, text, contact info, Wi-Fi credentials, and more. It can be scanned by any smartphone camera to instantly access the encoded information.",
  },
  {
    question: "Can I use the generated QR codes for commercial purposes?",
    answer:
      "Yes. QR codes generated by this tool are completely free to use for any purpose, including commercial use. There are no restrictions or watermarks.",
  },
  {
    question: "What formats can I download the QR code in?",
    answer:
      "You can download the QR code as a PNG image. The generated image is high resolution and suitable for both digital use and printing.",
  },
  {
    question: "Is there a limit to how much data a QR code can store?",
    answer:
      "QR codes can store up to 4,296 alphanumeric characters. However, shorter content produces simpler, more easily scannable codes. For best results, keep URLs and text concise.",
  },
  {
    question: "Do the QR codes expire?",
    answer:
      "No. QR codes generated here are static and never expire. They encode the data directly, so they work forever as long as the linked content (like a URL) remains available.",
  },
];

export default function QrCodeGeneratorPage() {
  const [text, setText] = useState("");
  const [qrUrl, setQrUrl] = useState("");
  const canvasRef = useRef<HTMLCanvasElement>(null);

  async function generate() {
    if (!text.trim()) return;
    try {
      const url = await QRCode.toDataURL(text, {
        width: 400,
        margin: 2,
        color: { dark: "#000000", light: "#ffffff" },
      });
      setQrUrl(url);
    } catch {
      setQrUrl("");
    }
  }

  function download() {
    if (!qrUrl) return;
    const a = document.createElement("a");
    a.href = qrUrl;
    a.download = "qrcode.png";
    a.click();
  }

  return (
    <div className="mx-auto max-w-4xl px-4 py-8">
      <JsonLd
        data={webApplicationSchema({
          name: "QR Code Generator",
          description:
            "Free online QR code generator. Create QR codes for URLs, text, Wi-Fi, and more. Download as PNG.",
          url: "https://toolpilot.pages.dev/tools/qr-code-generator",
          category: "UtilityApplication",
          keywords: ["qr code generator", "create qr code", "qr code maker", "free qr code"],
        })}
      />
      <JsonLd
        data={howToSchema({
          name: "How to Generate a QR Code Online",
          description: "Create a free QR code for any URL or text using ToolPilot.",
          steps: [
            { name: "Enter content", text: "Type or paste a URL, text, or any data into the input field." },
            { name: "Generate", text: "Click the Generate QR Code button to create your QR code." },
            { name: "Download", text: "Click Download PNG to save the QR code image to your device." },
          ],
        })}
      />
      <Breadcrumb
        items={[
          { label: "Home", href: "/" },
          { label: "Converters", href: "/#converter" },
          { label: "QR Code Generator", href: "/tools/qr-code-generator" },
        ]}
      />

      <h1 className="mb-2 text-3xl font-bold">QR Code Generator</h1>
      <p className="mb-6 text-gray-600">
        Generate free QR codes for URLs, text, Wi-Fi credentials, and more.
        Download as high-resolution PNG. No sign-up required.
      </p>

      <AdBanner slot="tool-top" format="horizontal" />

      <div className="grid gap-6 lg:grid-cols-2">
        <div>
          <textarea
            className="mb-4 w-full rounded-lg border border-gray-300 p-4 text-base focus:border-blue-500 focus:outline-none"
            rows={5}
            placeholder="Enter URL or text (e.g., https://example.com)"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <button
            onClick={generate}
            className="w-full rounded-lg bg-blue-600 px-6 py-3 text-sm font-medium text-white hover:bg-blue-700"
          >
            Generate QR Code
          </button>
        </div>
        <div className="flex flex-col items-center rounded-lg bg-white p-6">
          {qrUrl ? (
            <>
              <img src={qrUrl} alt="Generated QR Code" className="mb-4 h-64 w-64" />
              <button
                onClick={download}
                className="rounded-lg bg-blue-600 px-6 py-2 text-sm font-medium text-white hover:bg-blue-700"
              >
                Download PNG
              </button>
            </>
          ) : (
            <div className="flex h-64 w-64 items-center justify-center rounded-lg border-2 border-dashed border-gray-300 text-sm text-gray-400">
              QR code will appear here
            </div>
          )}
          <canvas ref={canvasRef} className="hidden" />
        </div>
      </div>

      <AdBanner slot="tool-mid" format="rectangle" />

      <section className="mt-8 rounded-lg bg-white p-6 text-sm text-gray-600">
        <h2 className="mb-2 text-lg font-semibold text-gray-900">What Is a QR Code?</h2>
        <p className="mb-3">
          A QR (Quick Response) code is a type of matrix barcode invented in 1994. It can encode URLs, plain text, contact information, Wi-Fi network credentials, and more. Any modern smartphone can scan QR codes using its built-in camera.
        </p>
        <h3 className="mb-1 font-semibold text-gray-900">Common Use Cases</h3>
        <ul className="list-inside list-disc space-y-1">
          <li>Linking to websites and landing pages</li>
          <li>Sharing Wi-Fi network credentials</li>
          <li>Digital business cards (vCards)</li>
          <li>Restaurant menus and event tickets</li>
          <li>App download links</li>
        </ul>
      </section>

      <FAQ items={faqs} />
      <AdBanner slot="tool-bottom" format="horizontal" />
    </div>
  );
}
